### ISSUE TITLE
add general nonlinear constraints (expression graph based)

### ISSUE THREAD

**Issue by leethargo** [leethargo/CSIP#12]
SCIP supports fairly general nonlinear constraints given as expression graph.

The expression graph could be input via the adjacency matrix and another vector for the symbolic meaning of the nodes.

**Comment by mlubin** [comment]
I'll be giving a talk next week at juliacon about this compact expression
graph data structure, can share the slides afterwards.

**Comment by leethargo** [comment]
Please do.

**Comment by mlubin** [comment]
Posted at http://www.mit.edu/~mlubin/juliacon2016.pdf. The basic idea is that you can encode all the information you need for an expression tree by using a single flat vector. Each element in the vector can be a struct which contains info about the expression node plus the index of its parent. For the purposes of a C API, it's better to avoid structs and just use multiple vectors of simple types.

This format doesn't match up with MathProgBase exactly (although it's not hard to translate), but I think this is a much more sane choice for a C API since it doesn't ask the user to build up an expression tree node-by-node.

**Comment by leethargo** [comment]
Thanks for slides! I'm looking forward to all the videos from JuliaCon, too.

**Comment by fserra** [comment]
So based on the slides of @mlubin we were able to implement this. See https://github.com/leethargo/CSIP/pull/22
Thanks!
