### ISSUE TITLE
decide on the data structure to store vars and cons

### ISSUE THREAD

**Issue by fserra** [leethargo/CSIP#8]
so what are the requirements? we want to delete variables and constraints? and then reuse those indices?

**Comment by leethargo** [comment]
I vote against deletion (for now). Mostly because I like the simplicity of the current solution.

If I remember correctly, deletion of variables is not even properly supported in SCIP. In fact, the FAQ recommends to fix the variable instead. But maybe that applies only for the solving stage?

Constraint deletion is supported, I guess, but we could also just `SCIPdeactiveCons` it and keep the pointer.

**Comment by fserra** [comment]
adding is enough. the current implementation allows for this.
